/*
--#########################################################################
--
-- Script Name  :  $Workfile:   bks_cr_cross_reference_item_22.sql  $ 
-- Header       :  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/bks_cr_cross_reference_item_22.sql-arc   1.0   Oct 30 2014 08:50:04   makuier  $ 
-- Revision     :  $Revision:   1.0  $
-- 
-- -----------------------------------------------------------------------
--
-- Description:
--
--
--
--#########################################################################*/

DELETE FROM CROSS_REFERENCE_ITEM WHERE GROUP_CODE = 'PRIC_SALES';

INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP030', 'PRIC_SALES', 'SP030', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP031', 'PRIC_SALES', 'SP031', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP032', 'PRIC_SALES', 'SP032', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP033', 'PRIC_SALES', 'SP033', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP034', 'PRIC_SALES', 'SP034', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP035', 'PRIC_SALES', 'SP035', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP036', 'PRIC_SALES', 'SP036', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP037', 'PRIC_SALES', 'SP037', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP038', 'PRIC_SALES', 'SP038', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP039', 'PRIC_SALES', 'SP039', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP040', 'PRIC_SALES', 'SP040', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP041', 'PRIC_SALES', 'SP041', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP042', 'PRIC_SALES', 'SP042', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP043', 'PRIC_SALES', 'SP043', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP044', 'PRIC_SALES', 'SP044', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP045', 'PRIC_SALES', 'SP045', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP046', 'PRIC_SALES', 'SP046', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP047', 'PRIC_SALES', 'SP047', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP048', 'PRIC_SALES', 'SP048', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP049', 'PRIC_SALES', 'SP049', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP050', 'PRIC_SALES', 'SP050', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP051', 'PRIC_SALES', 'SP051', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP052', 'PRIC_SALES', 'SP052', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP053', 'PRIC_SALES', 'SP053', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP054', 'PRIC_SALES', 'SP054', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP055', 'PRIC_SALES', 'SP055', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP056', 'PRIC_SALES', 'SP056', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP057', 'PRIC_SALES', 'SP057', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP058', 'PRIC_SALES', 'SP058', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP059', 'PRIC_SALES', 'SP059', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VP060', 'PRIC_SALES', 'SP060', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
