/*
--#########################################################################
--
-- Script Name  :  $Workfile:   bks_cr_cross_reference_item_26.sql  $ 
-- Header       :  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/bks_cr_cross_reference_item_26.sql-arc   1.0   May 14 2018 14:27:48   makuier  $ 
-- Revision     :  $Revision:   1.0  $
-- 
-- -----------------------------------------------------------------------
--
-- Description: PPM-196371
--
--#########################################################################*/
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP067' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR112' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI006;VP067', 'PRIC_SALES', 'PR112', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP072' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR116' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI006;VP072', 'PRIC_SALES', 'PR116', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP067' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR111' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP067', 'PRIC_SALES', 'PR111', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP072' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR115' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP072', 'PRIC_SALES', 'PR115', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
