/*
--#########################################################################
--
-- Script Name  :  $Workfile:   bks_cr_cross_reference_item_25.sql  $ 
-- Header       :  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/bks_cr_cross_reference_item_25.sql-arc   1.0   Jul 26 2016 12:51:42   makuier  $ 
-- Revision     :  $Revision:   1.0  $
-- 
-- -----------------------------------------------------------------------
--
-- Description: PPM-196371
--
--#########################################################################*/
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP061' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV027' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('V0003;VP061', 'PRIC_SALES', 'PV027', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV029' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV031' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV033' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV035' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('V0003;VP063', 'PRIC_SALES', 'PV035', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV037' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV039' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV041' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0003;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV043' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('V0003;VP068', 'PRIC_SALES', 'PV043', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP061' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV028' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('V0010;VP061', 'PRIC_SALES', 'PV028', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV030' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV032' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV034' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV036' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('V0010;VP063', 'PRIC_SALES', 'PV036', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV038' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV040' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV042' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'V0010;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PV044' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('V0010;VP068', 'PRIC_SALES', 'PV044', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP061' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI056' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI002;VP061', 'PRIC_SALES', 'PI056', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI058' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI060' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI062' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI064' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI002;VP063', 'PRIC_SALES', 'PI064', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP065' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI066' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP065' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI068' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI002;VP065', 'PRIC_SALES', 'PI068', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI070' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI072' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI074' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI076' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI002;VP068', 'PRIC_SALES', 'PI076', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP070' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI078' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP070' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI080' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI002;VP070', 'PRIC_SALES', 'PI080', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP061' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI057' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI003;VP061', 'PRIC_SALES', 'PI057', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI059' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI061' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI063' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI065' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI003;VP063', 'PRIC_SALES', 'PI065', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP065' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI067' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP065' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI069' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI003;VP065', 'PRIC_SALES', 'PI069', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI071' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI073' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI075' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI077' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI003;VP068', 'PRIC_SALES', 'PI077', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP070' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI079' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP070' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PI081' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI003;VP070', 'PRIC_SALES', 'PI081', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR076' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR078' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR080' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR082' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR084' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI006;VP063', 'PRIC_SALES', 'PR084', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP065' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR086' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP065' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR088' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI006;VP065', 'PRIC_SALES', 'PR088', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP066' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR090' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI006;VP066', 'PRIC_SALES', 'PR090', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR094' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR096' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR098' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR100' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR102' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI006;VP068', 'PRIC_SALES', 'PR102', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP070' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR104' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP070' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR106' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI006;VP070', 'PRIC_SALES', 'PR106', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI006;VP071' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR108' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI006;VP071', 'PRIC_SALES', 'PR108', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP061' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR071' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP061' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR072' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP061', 'PRIC_SALES', 'PR072', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR073' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR074' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR075' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR077' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR079' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR081' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP063' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR083' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP063', 'PRIC_SALES', 'PR083', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP065' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR085' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP065' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR087' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP065', 'PRIC_SALES', 'PR087', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP066' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR089' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP066', 'PRIC_SALES', 'PR089', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR091' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR092' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR093' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR095' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR097' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR099' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP068' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR101' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP068', 'PRIC_SALES', 'PR101', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP070' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR103' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP070' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR105' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP070', 'PRIC_SALES', 'PR105', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI009;VP071' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PR107' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER) VALUES ('VI009;VP071', 'PRIC_SALES', 'PR107', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-196371', sysdate, 101);
