/*
--#########################################################################
--
-- Script Name  :  $Workfile:   bks_cr_cross_reference_item_27.sql  $ 
-- Header       :  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/bks_cr_cross_reference_item_27.sql-arc   1.0   Oct 01 2018 15:16:00   makuier  $ 
-- Revision     :  $Revision:   1.0  $
-- 
-- -----------------------------------------------------------------------
--
-- Description: PPM-196371
--
--#########################################################################*/
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP500' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF001' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP500', 'PRIC_SALES', 'PF001', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP500' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF002' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP500', 'PRIC_SALES', 'PF002', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP501' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF003' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP501', 'PRIC_SALES', 'PF003', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP501' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF004' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP501', 'PRIC_SALES', 'PF004', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP502' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF005' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP502', 'PRIC_SALES', 'PF005', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP502' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF006' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP502', 'PRIC_SALES', 'PF006', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP503' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF007' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP503', 'PRIC_SALES', 'PF007', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP503' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF008' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP503', 'PRIC_SALES', 'PF008', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP504' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF009' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP504', 'PRIC_SALES', 'PF009', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP504' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF010' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP504', 'PRIC_SALES', 'PF010', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP505' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF011' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP505', 'PRIC_SALES', 'PF011', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP505' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF012' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP505', 'PRIC_SALES', 'PF012', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP506' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF013' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP506', 'PRIC_SALES', 'PF013', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP506' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF014' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP506', 'PRIC_SALES', 'PF014', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP507' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF015' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP507', 'PRIC_SALES', 'PF015', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP507' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF016' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP507', 'PRIC_SALES', 'PF016', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP508' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF017' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP508', 'PRIC_SALES', 'PF017', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP508' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF018' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP508', 'PRIC_SALES', 'PF018', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP509' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF019' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP509', 'PRIC_SALES', 'PF019', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP509' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF020' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP509', 'PRIC_SALES', 'PF020', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP510' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF021' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP510', 'PRIC_SALES', 'PF021', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP510' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF022' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP510', 'PRIC_SALES', 'PF022', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP511' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF023' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP511', 'PRIC_SALES', 'PF023', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP511' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF024' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP511', 'PRIC_SALES', 'PF024', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP512' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF025' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP512', 'PRIC_SALES', 'PF025', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP512' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF026' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP512', 'PRIC_SALES', 'PF026', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP513' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF027' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP513', 'PRIC_SALES', 'PF027', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP513' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF028' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP513', 'PRIC_SALES', 'PF028', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP514' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF029' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP514', 'PRIC_SALES', 'PF029', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP514' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF030' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP514', 'PRIC_SALES', 'PF030', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI002;VP515' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF031' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI002;VP515', 'PRIC_SALES', 'PF031', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);
DELETE FROM CROSS_REFERENCE_ITEM WHERE PRIMARY_VALUE = 'VI003;VP515' AND GROUP_CODE = 'PRIC_SALES' AND SECONDARY_VALUE = 'PF032' AND EFFECTIVE_DATE = to_date('01.01.1999', 'DD.MM.YYYY');
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
 VALUES ('VI003;VP515', 'PRIC_SALES', 'PF032', to_date('01.01.1999', 'DD.MM.YYYY'), 'ACTIVE', 'PPM-320858', sysdate, 101);

