/*
--#########################################################################
--
-- Script Name  :  $Workfile:   bks_cr_cross_reference_item_21.sql  $ 
-- Header       :  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/bks_cr_cross_reference_item_21.sql-arc   1.0   Mar 19 2012 11:00:42   makuier  $ 
-- Revision     :  $Revision:   1.0  $
-- 
-- -----------------------------------------------------------------------
--
-- Description:
--
--
--
--#########################################################################*/

DELETE FROM CROSS_REFERENCE_ITEM WHERE GROUP_CODE = 'SERV_VARIN'
AND PRIMARY_VALUE IN ('V0001','V0002','V0004','V0011');

INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0001', 'SERV_VARIN', 'voicePremium', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0002', 'SERV_VARIN', 'p2p', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0004', 'SERV_VARIN', 'voiceBasis', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0011', 'SERV_VARIN', 'p2p', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);

DELETE FROM CROSS_REFERENCE_ITEM WHERE GROUP_CODE = 'SERV_ACCES'
AND PRIMARY_VALUE IN ('V0001','V0002','V0004');

INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0001', 'SERV_ACCES', 'preselect', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0002', 'SERV_ACCES', 'preselect', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0004', 'SERV_ACCES', 'preselect', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);

DELETE FROM CROSS_REFERENCE_ITEM WHERE GROUP_CODE = 'SERV_FU_MA'
AND PRIMARY_VALUE IN ('Wh004','Wh010');

INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('Wh004', 'SERV_FU_MA', 'Internet', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('Wh010', 'SERV_FU_MA', 'Sprache', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
