/*
--#########################################################################
--
-- Script Name  :  $Workfile:   bks_cr_cross_reference_item_23.sql  $ 
-- Header       :  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/bks_cr_cross_reference_item_23.sql-arc   1.0   Nov 25 2014 08:15:30   makuier  $ 
-- Revision     :  $Revision:   1.0  $
-- 
-- -----------------------------------------------------------------------
--
-- Description:
--
--
--
--#########################################################################*/

DELETE FROM CROSS_REFERENCE_ITEM WHERE GROUP_CODE = 'PRIC_SALES';

INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP030', 'PRIC_SALES', 'PV005', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP031', 'PRIC_SALES', 'PV007', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP035', 'PRIC_SALES', 'PV009', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP036', 'PRIC_SALES', 'PV015', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP037', 'PRIC_SALES', 'PV017', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP042', 'PRIC_SALES', 'PV019', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP044', 'PRIC_SALES', 'PV021', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP052', 'PRIC_SALES', 'PV023', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0003;VP054', 'PRIC_SALES', 'PV025', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP030', 'PRIC_SALES', 'PV006', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP031', 'PRIC_SALES', 'PV008', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP035', 'PRIC_SALES', 'PV010', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP036', 'PRIC_SALES', 'PV016', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP037', 'PRIC_SALES', 'PV018', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP042', 'PRIC_SALES', 'PV020', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP044', 'PRIC_SALES', 'PV022', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP052', 'PRIC_SALES', 'PV024', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('V0010;VP054', 'PRIC_SALES', 'PV026', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP030', 'PRIC_SALES', 'PI004', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP031', 'PRIC_SALES', 'PI006', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP032', 'PRIC_SALES', 'PI008', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP033', 'PRIC_SALES', 'PI010', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP035', 'PRIC_SALES', 'PI012', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP036', 'PRIC_SALES', 'PI016', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP037', 'PRIC_SALES', 'PI018', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP038', 'PRIC_SALES', 'PI020', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP039', 'PRIC_SALES', 'PI022', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP041', 'PRIC_SALES', 'PI024', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP042', 'PRIC_SALES', 'PI026', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP043', 'PRIC_SALES', 'PI028', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP044', 'PRIC_SALES', 'PI030', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP045', 'PRIC_SALES', 'PI032', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP046', 'PRIC_SALES', 'PI034', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP047', 'PRIC_SALES', 'PI036', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP048', 'PRIC_SALES', 'PI038', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP051', 'PRIC_SALES', 'PI040', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP052', 'PRIC_SALES', 'PI042', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP053', 'PRIC_SALES', 'PI044', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP054', 'PRIC_SALES', 'PI046', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP055', 'PRIC_SALES', 'PI048', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP056', 'PRIC_SALES', 'PI050', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP057', 'PRIC_SALES', 'PI052', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI002;VP058', 'PRIC_SALES', 'PI054', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP030', 'PRIC_SALES', 'PI005', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP031', 'PRIC_SALES', 'PI007', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP032', 'PRIC_SALES', 'PI009', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP033', 'PRIC_SALES', 'PI011', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP036', 'PRIC_SALES', 'PI017', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP037', 'PRIC_SALES', 'PI019', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP038', 'PRIC_SALES', 'PI021', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP039', 'PRIC_SALES', 'PI023', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP041', 'PRIC_SALES', 'PI025', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP042', 'PRIC_SALES', 'PI027', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP043', 'PRIC_SALES', 'PI029', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP044', 'PRIC_SALES', 'PI031', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP045', 'PRIC_SALES', 'PI033', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP046', 'PRIC_SALES', 'PI035', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP047', 'PRIC_SALES', 'PI037', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP048', 'PRIC_SALES', 'PI039', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP051', 'PRIC_SALES', 'PI041', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP052', 'PRIC_SALES', 'PI043', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP053', 'PRIC_SALES', 'PI045', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP054', 'PRIC_SALES', 'PI047', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP055', 'PRIC_SALES', 'PI049', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP056', 'PRIC_SALES', 'PI051', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP057', 'PRIC_SALES', 'PI053', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI003;VP058', 'PRIC_SALES', 'PI055', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP030', 'PRIC_SALES', 'PR010', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP031', 'PRIC_SALES', 'PR012', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP032', 'PRIC_SALES', 'PR014', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP033', 'PRIC_SALES', 'PR016', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP034', 'PRIC_SALES', 'PR018', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP035', 'PRIC_SALES', 'PR020', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP036', 'PRIC_SALES', 'PR030', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP037', 'PRIC_SALES', 'PR032', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP038', 'PRIC_SALES', 'PR034', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP039', 'PRIC_SALES', 'PR036', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP040', 'PRIC_SALES', 'PR038', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP042', 'PRIC_SALES', 'PR040', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP044', 'PRIC_SALES', 'PR042', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP045', 'PRIC_SALES', 'PR044', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP046', 'PRIC_SALES', 'PR046', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP047', 'PRIC_SALES', 'PR048', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP048', 'PRIC_SALES', 'PR050', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP049', 'PRIC_SALES', 'PR052', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP050', 'PRIC_SALES', 'PR054', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP052', 'PRIC_SALES', 'PR056', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP054', 'PRIC_SALES', 'PR058', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP055', 'PRIC_SALES', 'PR060', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP056', 'PRIC_SALES', 'PR062', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP057', 'PRIC_SALES', 'PR064', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP058', 'PRIC_SALES', 'PR066', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP059', 'PRIC_SALES', 'PR068', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI006;VP060', 'PRIC_SALES', 'PR070', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP030', 'PRIC_SALES', 'PR009', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP031', 'PRIC_SALES', 'PR011', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP032', 'PRIC_SALES', 'PR013', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP033', 'PRIC_SALES', 'PR015', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP034', 'PRIC_SALES', 'PR017', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP035', 'PRIC_SALES', 'PR019', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP036', 'PRIC_SALES', 'PR029', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP037', 'PRIC_SALES', 'PR031', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP038', 'PRIC_SALES', 'PR033', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP039', 'PRIC_SALES', 'PR035', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP040', 'PRIC_SALES', 'PR037', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP042', 'PRIC_SALES', 'PR039', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP044', 'PRIC_SALES', 'PR041', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP045', 'PRIC_SALES', 'PR043', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP046', 'PRIC_SALES', 'PR045', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP047', 'PRIC_SALES', 'PR047', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP048', 'PRIC_SALES', 'PR049', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP049', 'PRIC_SALES', 'PR051', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP050', 'PRIC_SALES', 'PR053', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP052', 'PRIC_SALES', 'PR055', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP054', 'PRIC_SALES', 'PR057', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP055', 'PRIC_SALES', 'PR059', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP056', 'PRIC_SALES', 'PR061', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP057', 'PRIC_SALES', 'PR063', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP058', 'PRIC_SALES', 'PR065', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP059', 'PRIC_SALES', 'PR067', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
INSERT INTO CROSS_REFERENCE_ITEM (PRIMARY_VALUE, GROUP_CODE, SECONDARY_VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('VI009;VP060', 'PRIC_SALES', 'PR069', TO_DATE ('01.01.1999 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'crd_user', SYSDATE, 1);
																																																																							 
