/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_269.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_269.sql-arc   1.0   May 20 2016 15:13:58   sibani.panda  $ 
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- Ref data for PPM 157167 TKG46 Requirements with changes
--
--#########################################################################*/

DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-2' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-2', 'V0002', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0003', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-3' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-3', 'V0002', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0010', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-4' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-4', 'V0002', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0010', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-5' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-5', 'V0002', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0011', 'Functions.Voice.VoicePBXConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-6' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-6', 'V0002', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0011', 'Functions.Voice.VoicePBXConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-7' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-7', 'V0002', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0003', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-8' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-8', 'V0002', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0003', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-9' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-9', 'V0002', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0010', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-10' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-10', 'V0002', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0010', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-11' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-11', 'V0002', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0011', 'Functions.Voice.VoicePBXConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-12' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-12', 'V0002', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'V0011', 'Functions.Voice.VoicePBXConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-13' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-13', 'I1305', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1305', 'Functions.TvCenter.TvCenterBundledConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-14' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-14', 'I1305', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1305', 'Functions.TvCenter.TvCenterBundledConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-15' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-15', 'I1305', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1305', 'Functions.TvCenter.TvCenterBundledConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-16' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-16', 'I1305', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1305', 'Functions.TvCenter.TvCenterBundledConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-17' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-17', 'I1410', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1410', 'Functions.SafetyPackage.SafetyPackageConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-18' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-18', 'I1410', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1410', 'Functions.SafetyPackage.SafetyPackageConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-19' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-19', 'I1410', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1410', 'Functions.SafetyPackage.SafetyPackageConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-20' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-20', 'I1410', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1410', 'Functions.SafetyPackage.SafetyPackageConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-21' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-21', 'VI203', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI006', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-22' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-22', 'VI203', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI006', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-23' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-23', 'VI203', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI006', 'Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-24' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-24', 'VI203', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI006', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-25' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-25', 'VI203', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI009', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-26' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-26', 'VI203', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI009', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-27' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-27', 'VI203', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI009', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-28' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-28', 'VI203', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI009', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-29' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-29', 'I1203', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1213', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-30' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-30', 'I1203', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1213', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-31' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-31', 'I1203', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1213', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-32' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-32', 'I1203', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1213', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-33' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-33', 'VI208', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI018', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-34' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-34', 'VI208', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI018', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-35' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-35', 'VI208', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI018', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-36' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-36', 'VI208', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI018', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-37' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-37', 'VI208', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI019', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-38' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-38', 'VI208', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI019', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingNam', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-39' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-39', 'VI208', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI019', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-40' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-40', 'VI208', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI019', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-41' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-41', 'I1208', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1219', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-42' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-42', 'I1208', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1219', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-43' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-43', 'I1208', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1219', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-44' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-44', 'I1208', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1219', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-45' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-45', 'VI202', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI002', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-46' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-46', 'VI202', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI002', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-47' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-47', 'VI202', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI002', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-48' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-48', 'VI202', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI002', 'Functions.Voice.VoiceBasisConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-49' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-49', 'VI202', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI003', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-50' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-50', 'VI202', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI003', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-51' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-51', 'VI202', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI003', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-52' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-52', 'VI202', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'VI003', 'Functions.Voice.VoicePremiumConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-53' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-53', 'I1204', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1210', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-54' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-54', 'I1204', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1210', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-55' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-55', 'I1204', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1210', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-56' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-56', 'I1204', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I1210', 'Functions.Internet.AdslInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-57' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-57', 'I1204', 'V0991', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I121z', 'Functions.Internet.FttxInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-58' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-58', 'I1204', 'V0991', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I121z', 'Functions.Internet.FttxInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-59' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-59', 'I1204', 'V0992', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I121z', 'Functions.Internet.FttxInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceCode', null, null, null, null, null, null, null);
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id = 'PPM157167-60' AND valid_from = to_date('01.01.1979', 'DD.MM.YYYY') AND valid_until = to_date('01.01.3000', 'DD.MM.YYYY');
INSERT INTO BKS_GENERIC_CONFIGURATION (value_id, source_product_code, source_service_code, source_service_char_code, source_field_number, source_column, target_attribute_path, default_value, value_type, apply_method, target_multiple_occurrence, rds_id, valid_from, valid_until, parent_service_code, som_attribute_path, prefix, dependent_char_code, main_bundle_access, sid_attribute_path, open_order_indicator, fixed_value, introduction_version) VALUES ('PPM157167-60', 'I1204', 'V0992', null, null, 'SERVICE_BILLING_NAME', null, null, 'CONTRACT', null, 'N', null, to_date('01.01.1979', 'DD.MM.YYYY'), to_date('01.01.3000', 'DD.MM.YYYY'), 'I121z', 'Functions.Internet.FttxInternetConfiguration.TariffOptionsList.Existing.TariffOption.ServiceBillingName', null, null, null, null, null, null, null);
