/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_268.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_268.sql-arc   1.0   Apr 27 2016 19:24:56   lejam  $ 
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- 
--
--#########################################################################*/

DELETE FROM BKS_GENERIC_CONFIGURATION WHERE VALUE_ID IN ('BKSGC_14510');
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE VALUE_ID IN ('BKSGC_14511');
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE VALUE_ID IN ('BKSGC_4208');
DELETE FROM BKS_GENERIC_CONFIGURATION WHERE VALUE_ID IN ('BKSGC_4210');

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_14510', 'I1207', 'I1216', 'V0826', null, null, null, null, 'CONFIGURED_VALUE', 'convertBandwidthBDSLVDSL', 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Internet.AdslInternetConfiguration.DSLBandwidth.Existing', null, 'V009C', null, null, null, 'VDSL', null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_14511', 'I1207', 'I1216', 'V0876', null, null, null, null, 'CONFIGURED_VALUE', 'convertBandwidthBDSLVDSL', 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Internet.AdslInternetConfiguration.DesiredBandwidth.Existing', null, 'V009C', null, null, null, 'VDSL', null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_4208', 'I1207', 'I1216', 'V0826', null, null, null, null, 'CONFIGURED_VALUE', 'convertBandwidthBDSLADSL', 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Internet.AdslInternetConfiguration.DSLBandwidth.Existing', null, 'V009C', null, null, null, ';VDSL', null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_4210', 'I1207', 'I1216', 'V0876', null, null, null, null, 'CONFIGURED_VALUE', 'convertBandwidthBDSLADSL', 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Internet.AdslInternetConfiguration.DesiredBandwidth.Existing', null, 'V009C', null, null, null, ';VDSL', null);
