/*
--#########################################################################
--
-- Script Name          :  $Workfile:   upd_crd_general_code_item_str_to_rem.sql  $ 
-- Header               :  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_crd_general_code_item_str_to_rem.sql-arc   1.0   Dec 05 2014 14:19:26   makuier  $ 
-- Revision             :  $Revision:   1.0  $
-- 
---------------------------------------------------------------------------
--
--  IT-k-25454
-- 
--
--
--
--#########################################################################*/

ALTER session SET nls_date_format='DD.MM.YYYY HH24:MI:SS';


DELETE FROM general_code_item
WHERE GROUP_CODE = 'STR_TO_REM';

DELETE FROM general_code_group
WHERE GROUP_CODE = 'STR_TO_REM';
-------------------------------------------------------
INSERT INTO GENERAL_CODE_GROUP (GROUP_CODE, DESCRIPTION, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER, DESCRIPTION_TRANSLATION_ID, COMPONENT, DATA_TYPE, RESPONSIBLE)
    VALUES ('STR_TO_REM', 'Strings to disregard in names', 'crd_user', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 1004, NULL, 'CCM', NULL, 'CCM Entwicklung');
	

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'UND', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'INHABER', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'BETRIEBSWIRT', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'BETRIEBSWIRT(BA)', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'BETRIEBSWIRT(FH)', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'DIPL', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'FINANZWIRT', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'FINANZWIRTIN', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'ING', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', '(BA)', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', '(FH)', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'OEC', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'KFM', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'MED', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'VOLKSWIRT', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'DR', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'JUR', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'DENT', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'NAT', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'PROF', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'PSYCHOLOGE', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'PSYCHOLOGIN', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'WIRTSCHAFTING', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('STR_TO_REM', 'WIRTSCHAFTING/FH', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Strings to disregard in names', 'Strings to disregard in names', NULL, NULL, 'crd_user', sysdate, 1);




