/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_290.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_287.sql-arc   1.0    
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
-- 
--
--#########################################################################*/
delete from BKS_GENERIC_CONFIGURATION
where VALUE_ID IN ('BKSGC_17227','BKSGC_17228','BKSGC_17229','BKSGC_17230','BKSGC_17231',
'BKSGC_17232','BKSGC_17233','BKSGC_17234','BKSGC_17235');



Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17227','I1207','V011A','V0111',NULL,'CITY_SUFFIX_NAME',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.CitySuffix',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17228','I1207','V011A','V0111',NULL,'POST_OFFICE_BOX',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.PostOfficeBox',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17229','I1207','V011A','V0111',NULL,'STREET_NAME',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.Street',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17230','I1207','V011A','V0111',2,'STREET_NUMBER',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.StreetNumberSuffix',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17231','I1207','V011A','V0111',NULL,'POSTAL_CODE',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.PostalCode',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17232','I1207','V011A','V0111',NULL,'CITY_NAME',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.City',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17233','I1207','V011A','V0111',1,'STREET_NUMBER',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.StreetNumber',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17234','I1207','V011A','V0111',NULL,'COUNTRY_RD',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.Country',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17235','I1207','V011A','V0111',NULL,'STREET_NUMBER_SUFFIX',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.StreetNumberSuffix',NULL,NULL,NULL,NULL,NULL,NULL,null);

