/*--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_304.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_302.sql-arc   1.0    
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
-- RMS 169758 - PPM 196251_278654 "One Net Business Release 1.1 Lot B
--
--#########################################################################*/

DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id IN ('BKSGC_17261','BKSGC_17262','BKSGC_17263','BKSGC_17264');

Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values 
  ('BKSGC_17261','I1203','V018U',null,null,null,null,'V018U','SERVICE',null,'N',null,to_date('01.01.1979 12.00.00','DD.MM.YYYY HH.MI.SS'),to_date('01.01.3000 12.00.00','DD.MM.YYYY HH.MI.SS'),null,'Functions.Internet.AdslInternetConfiguration.DSLBandwidth.Existing',null,null,null,null,null,null,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values 
  ('BKSGC_17262','I1203','V018V',null,null,null,null,'V018V','SERVICE',null,'N',null,to_date('01.01.1979 12.00.00','DD.MM.YYYY HH.MI.SS'),to_date('01.01.3000 12.00.00','DD.MM.YYYY HH.MI.SS'),null,'Functions.Internet.AdslInternetConfiguration.DSLBandwidth.Existing',null,null,null,null,null,null,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values 
  ('BKSGC_17263','I1209','V018U',null,null,null,null,'V018U','SERVICE',null,'N',null,to_date('01.01.1979 12.00.00','DD.MM.YYYY HH.MI.SS'),to_date('01.01.3000 12.00.00','DD.MM.YYYY HH.MI.SS'),null,'Functions.Internet.AdslInternetConfiguration.DSLBandwidth.Existing',null,null,null,null,null,null,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values 
  ('BKSGC_17264','I1209','V018V',null,null,null,null,'V018V','SERVICE',null,'N',null,to_date('01.01.1979 12.00.00','DD.MM.YYYY HH.MI.SS'),to_date('01.01.3000 12.00.00','DD.MM.YYYY HH.MI.SS'),null,'Functions.Internet.AdslInternetConfiguration.DSLBandwidth.Existing',null,null,null,null,null,null,null);
