/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_130.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_130.sql-arc   1.0   Jul 25 2011 12:43:30   wlazlow  $ 
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- SPN-BKS-000114232
--
--#########################################################################*/


DELETE FROM BKS_GENERIC_CONFIGURATION WHERE VALUE_ID IN ('BKSGC_11586','BKSGC_11587','BKSGC_11588','BKSGC_11589','BKSGC_11590','BKSGC_11591','BKSGC_11592','BKSGC_11593');

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION) values ('BKSGC_11586', '-', 'V0114', null, null, 'SERVICE_CODE', null, null, 'CONTRACT', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Hardware.HardwareConfiguration.HardwareServiceCode.Existing', null, null, null, null, null, null, null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION) values ('BKSGC_11587', '-', 'V0114', null, null, 'SERVICE_SUBSCRIPTION_DEP_ID', null, null, 'CONTRACT', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Hardware.RefFunctionID.Existing', 'F', null, null, null, null, null, null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION) values ('BKSGC_11588', '-', 'V0114', null, null, 'SERVICE_SUBSCRIPTION_ID', null, null, 'CONTRACT', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Hardware.ID', 'F', null, null, null, null, null, null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION) values ('BKSGC_11589', '-', 'V0114', null, null, '-', null, 'S', 'CONTRACT', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Hardware.CcbId.Type', null, null, null, null, null, null, null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION) values ('BKSGC_11590', '-', 'V0114', null, null, 'SERVICE_SUBSCRIPTION_ID', null, null, 'CONTRACT', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Hardware.CcbId.Existing', null, null, null, null, null, null, null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION) values ('BKSGC_11591', '-', 'V0114', null, null, '-', null, 'IGNORE', 'CONTRACT', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Hardware.ProcessingType', null, null, null, null, null, null, null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION) values ('BKSGC_11592', '-', 'V0114', 'V0885', null, null, null, null, 'CONFIGURED_VALUE', 'convertOpmToDate', 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Hardware.HardwareConfiguration.DeliveryDate.Existing', null, null, null, null, null, null, null);

insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION) values ('BKSGC_11593', '-', 'V0114', 'V0884', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), null, 'Functions.Hardware.HardwareConfiguration.DeliveryNoteNumber.Existing', null, null, null, null, null, null, null);



