/*
--#########################################################################
--
-- Script name: $Workfile $ 
-- Header     : $Header $ 
-- Revision   : $Revision $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- SPN-BKS-000084632 "The service HoleVertriebspaketDetails does not populate Sprache.Tarifoption"
--
--#########################################################################*/

alter session set nls_date_format = 'DD.MM.YYYY';

delete from BKS_GENERIC_CONFIGURATION
where TARGET_ATTRIBUTE_PATH = 'Sprache.Tarifoption.Tarifoption';

insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0259','V0001','V0290',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0260','V0001','V0291',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0261','V0001','V0293',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Option','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0262','V0001','V0299',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Option','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0263','V0001','V0300',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat 1','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0264','V0001','V0301',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat 2','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0265','V0001','V0302',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat (S0)','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0266','V0001','V0940',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0267','V0001','V0941',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 150','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0268','V0001','V0942',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0269','V0001','V0943',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 600','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0270','V0001','V0944',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 900','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0271','V0001','V0945',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1800','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0272','V0001','V1002',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0273','V0001','V1048',null,null,null,'Sprache.Tarifoption.Tarifoption','Vodafone-National-Mobile-Group','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0274','V0001','V1049',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0275','V0001','V1050',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0276','V0001','V1051',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0277','V0001','V1052',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0278','V0001','V1053',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0279','V0001','V1054',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0280','V0001','V1055',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 5.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0281','V0001','V1056',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 10.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0282','V0001','V1057',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 15.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0283','V0001','V1058',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 20.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0284','V0001','V1059',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 25.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0285','V0001','V1060',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 30.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0286','V0001','V1061',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 35.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0287','V0001','V1062',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 40.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0288','V0001','V1063',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0289','V0001','V1064',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 200','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0290','V0001','V1065',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0291','V0001','V1066',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 400','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0292','V0001','V1067',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0293','V0001','V1068',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0294','V0001','V1069',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 1.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0295','V0001','V1070',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0296','V0001','V1071',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 2.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0297','V0001','V1072',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0298','V0001','V1073',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 3.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0299','V0001','V1074',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0300','V0001','V1075',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0301','V0001','V1076',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 200','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0302','V0001','V1077',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0303','V0001','V1078',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 400','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0304','V0001','V1079',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0305','V0001','V1080',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0306','V0001','V1081',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0307','V0001','V1082',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0308','V0001','V1083',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 2.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0309','V0001','V1084',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0310','V0001','V1085',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 3.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0311','V0001','V1086',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0312','V0001','V1087',null,null,null,'Sprache.Tarifoption.Tarifoption','National-Mobile-Flat Vodafone','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0313','V0002','V0041',null,null,null,'Sprache.Tarifoption.Tarifoption','dsl flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0314','V0002','V0042',null,null,null,'Sprache.Tarifoption.Tarifoption','dsl isdn flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0315','V0002','V0043',null,null,null,'Sprache.Tarifoption.Tarifoption','isdn flat 64','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0316','V0002','V0222',null,null,null,'Sprache.Tarifoption.Tarifoption','Aktion Profi flat Paket','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0317','V0002','V0229',null,null,null,'Sprache.Tarifoption.Tarifoption','DSL flat special','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0318','V0002','V0238',null,null,null,'Sprache.Tarifoption.Tarifoption','telefon flat special','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0319','V0002','V0290',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0320','V0002','V0291',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0321','V0002','V0293',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Option','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0322','V0002','V0295',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins Vodafone D2-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0323','V0002','V0296',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche T-Mobile-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0324','V0002','V0297',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche E-Plus-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0325','V0002','V0298',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche O2-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0326','V0002','V0300',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat 1','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0327','V0002','V0301',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat 2','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0328','V0002','V0940',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0329','V0002','V0941',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 150','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0330','V0002','V0942',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0331','V0002','V0943',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 600','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0332','V0002','V0944',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 900','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0333','V0002','V0945',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1800','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0334','V0002','V1002',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0335','V0002','V1048',null,null,null,'Sprache.Tarifoption.Tarifoption','Vodafone-National-Mobile-Group','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0336','V0002','V1049',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0337','V0002','V1050',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0338','V0002','V1051',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0339','V0002','V1052',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0340','V0002','V1053',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0341','V0002','V1054',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0342','V0002','V1055',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 5.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0343','V0002','V1056',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 10.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0344','V0002','V1057',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 15.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0345','V0002','V1058',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 20.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0346','V0002','V1059',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 25.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0347','V0002','V1060',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 30.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0348','V0002','V1061',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 35.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0349','V0002','V1062',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 40.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0350','V0002','V1063',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0351','V0002','V1064',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 200','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0352','V0002','V1065',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0353','V0002','V1066',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 400','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0354','V0002','V1067',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0355','V0002','V1068',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0356','V0002','V1069',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 1.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0357','V0002','V1070',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0358','V0002','V1071',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 2.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0359','V0002','V1072',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0360','V0002','V1073',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 3.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0361','V0002','V1074',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0362','V0002','V1075',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0363','V0002','V1076',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 200','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0364','V0002','V1077',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0365','V0002','V1078',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 400','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0366','V0002','V1079',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0367','V0002','V1080',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0368','V0002','V1081',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0369','V0002','V1082',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0370','V0002','V1083',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 2.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0371','V0002','V1084',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0372','V0002','V1085',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 3.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0373','V0002','V1086',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0374','V0002','V1087',null,null,null,'Sprache.Tarifoption.Tarifoption','National-Mobile-Flat Vodafone','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0375','VI202','V0290',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0376','VI202','V0291',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0377','VI202','V0293',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Option','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0378','VI202','V0295',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins Vodafone D2-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0379','VI202','V0296',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche T-Mobile-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0380','VI202','V0297',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche E-Plus-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0381','VI202','V0298',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche O2-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0382','VI202','V0300',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat 1','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0383','VI202','V0301',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat 2','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0384','VI202','V1049',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0385','VI202','V1050',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0386','VI202','V1051',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0387','VI202','V1052',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0388','VI202','V1053',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0389','VI202','V1054',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0390','VI202','V1055',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 5.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0391','VI202','V1056',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 10.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0392','VI202','V1057',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 15.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0393','VI202','V1058',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 20.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0394','VI202','V1059',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 25.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0395','VI202','V1060',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 30.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0396','VI202','V1061',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 35.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0397','VI202','V1062',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 40.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0398','VI202','V1063',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0399','VI202','V1064',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 200','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0400','VI202','V1065',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0401','VI202','V1066',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 400','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0402','VI202','V1067',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0403','VI202','V1068',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0404','VI202','V1069',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 1.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0405','VI202','V1070',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0406','VI202','V1071',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 2.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0407','VI202','V1072',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0408','VI202','V1073',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 3.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0409','VI202','V1074',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0410','VI202','V1075',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0411','VI202','V1076',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 200','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0412','VI202','V1077',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0413','VI202','V1078',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 400','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0414','VI202','V1079',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0415','VI202','V1080',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0416','VI202','V1081',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0417','VI202','V1082',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0418','VI202','V1083',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 2.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0419','VI202','V1084',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0420','VI202','V1085',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 3.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0421','VI202','V1086',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0422','VI202','V1087',null,null,null,'Sprache.Tarifoption.Tarifoption','National-Mobile-Flat Vodafone','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0423','VI203','V0293',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Option','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0424','VI203','V0295',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins Vodafone D2-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0425','VI203','V0296',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche T-Mobile-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0426','VI203','V0297',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche E-Plus-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0427','VI203','V0298',null,null,null,'Sprache.Tarifoption.Tarifoption','Mobil-Flat ins deutsche O2-Netz','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0428','VI203','V0300',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat 1','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0429','VI203','V0301',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat 2','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0430','VI203','V1049',null,null,null,'Sprache.Tarifoption.Tarifoption','Euro-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0431','VI203','V1050',null,null,null,'Sprache.Tarifoption.Tarifoption','International-Flat','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0432','VI203','V1051',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0433','VI203','V1052',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0434','VI203','V1053',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0435','VI203','V1054',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0436','VI203','V1055',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 5.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0437','VI203','V1056',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 10.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0438','VI203','V1057',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 15.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0439','VI203','V1058',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 20.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0440','VI203','V1059',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 25.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0441','VI203','V1060',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 30.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0442','VI203','V1061',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 35.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0443','VI203','V1062',null,null,null,'Sprache.Tarifoption.Tarifoption','national minutes 40.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0444','VI203','V1063',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0445','VI203','V1064',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 200','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0446','VI203','V1065',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0447','VI203','V1066',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 400','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0448','VI203','V1067',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0449','VI203','V1068',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0450','VI203','V1069',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 1.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0451','VI203','V1070',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0452','VI203','V1071',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 2.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0453','VI203','V1072',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0454','VI203','V1073',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 3.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0455','VI203','V1074',null,null,null,'Sprache.Tarifoption.Tarifoption','international minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0456','VI203','V1075',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 100','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0457','VI203','V1076',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 200','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0458','VI203','V1077',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 300','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0459','VI203','V1078',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 400','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0460','VI203','V1079',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0461','VI203','V1080',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0462','VI203','V1081',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 1.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0463','VI203','V1082',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 2.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0464','VI203','V1083',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 2.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0465','VI203','V1084',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 3.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0466','VI203','V1085',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 3.500','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0467','VI203','V1086',null,null,null,'Sprache.Tarifoption.Tarifoption','mobile minutes 4.000','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0468','VI203','V1087',null,null,null,'Sprache.Tarifoption.Tarifoption','National-Mobile-Flat Vodafone','SERVICE',null,'N',null,'01.01.1979','01.01.3000');
