/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_296.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_287.sql-arc   1.0    
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
-- 
--
--#########################################################################*/
delete from BKS_GENERIC_CONFIGURATION
where VALUE_ID IN ('BKSGC_17249','BKSGC_17250','BKSGC_17251',
'BKSGC_17252','BKSGC_17253','BKSGC_17254','BKSGC_17255');

Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17249','I1207','V011A','V0111',NULL,'CITY_SUFFIX_NAME',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.CitySuffix',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17250','I1207','V011A','V0111',2,'STREET_NUMBER',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.StreetNumberSuffix',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17251','I1207','V011A','V0111',NULL,'POSTAL_CODE',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.PostalCode',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17252','I1207','V011A','V0111',NULL,'CITY_NAME',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.City',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17253','I1207','V011A','V0111',1,'STREET_NUMBER',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.StreetNumber',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17254','I1207','V011A','V0111',NULL,'COUNTRY_RD',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.Country',NULL,NULL,NULL,NULL,NULL,NULL,null);
Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION) values
 ('BKSGC_17255','I1207','V011A','V0111',NULL,'STREET_NUMBER_SUFFIX',NULL,NULL,'ADDRESS',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Hardware.HardwareConfiguration.HardwareMailingAddress.Existing.StreetNumberSuffix',NULL,NULL,NULL,NULL,NULL,NULL,null);
