/*--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_306.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_302.sql-arc   1.0    
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
-- RMS 169758 - PPM 196251_278654 "One Net Business Release 1.1 Lot B
--
--#########################################################################*/

DELETE FROM BKS_GENERIC_CONFIGURATION WHERE value_id IN ('BKSGC_15087','BKSGC_14508','BKSGC_14266','BKSGC_14267');

INSERT INTO BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION)  VALUES 
   ('BKSGC_15087','I1209','I1203','I0104',NULL,NULL,NULL,'N','CONFIGURED_VALUE','convertToBoolean','N',NULL,TO_DATE ('01.01.1979 00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00','DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Internet.AdslInternetConfiguration.DisableInternetUsageIndicator.Existing',NULL,NULL,NULL,NULL,NULL,NULL,'16.0');
INSERT INTO BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION)  VALUES 
   ('BKSGC_14508','I1203','I1213','I0104',NULL,NULL,NULL,'N','CONFIGURED_VALUE','convertToBoolean','N',NULL,TO_DATE ('01.01.1979 00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00','DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Internet.AdslInternetConfiguration.DisableInternetUsageIndicator.Existing',NULL,NULL,NULL,NULL,NULL,NULL,'16.0');
INSERT INTO BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION)  VALUES 
   ('BKSGC_14266','I1207','I1216','I0104',NULL,NULL,NULL,'N','CONFIGURED_VALUE','convertToBoolean','N',NULL,TO_DATE ('01.01.1979 00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00','DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Internet.AdslInternetConfiguration.DisableInternetUsageIndicator.Existing',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION)  VALUES 
   ('BKSGC_14267','I1207','I1215','I0104',NULL,NULL,NULL,'N','CONFIGURED_VALUE','convertToBoolean','N',NULL,TO_DATE ('01.01.1979 00:00:00','DD.MM.YYYY HH24:MI:SS'),TO_DATE ('01.01.3000 00:00:00','DD.MM.YYYY HH24:MI:SS'),NULL,'Functions.Internet.SdslInternetConfiguration.DisableInternetUsageIndicator.Existing',NULL,NULL,NULL,NULL,NULL,NULL,NULL);