/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_138.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_138.sql-arc   1.0   Aug 24 2011 11:25:20   wlazlow  $ 
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- Handling of the I1336 characteristic -  SapOrderId
--
--
--#########################################################################*/



delete FROM BKS_GENERIC_CONFIGURATION t where t.value_id in
( 'BKSGC_11671','BKSGC_11672', 'BKSGC_11673', 'BKSGC_11674', 'BKSGC_11675', 'BKSGC_11676');



insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11671', 'I1208', 'I1294', 'I1336', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'I1290', 'Functions.Hardware.HardwareConfiguration.SapOrderId.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11672', 'V0002', 'I1359', 'I1336', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'V0003', 'Functions.Hardware.HardwareConfiguration.SapOrderId.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11673', 'V0002', 'I1359', 'I1336', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'V0010', 'Functions.Hardware.HardwareConfiguration.SapOrderId.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11674', 'I1204', 'I1359', 'I1336', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'I1210', 'Functions.Hardware.HardwareConfiguration.SapOrderId.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11675', 'I1203', 'I1359', 'I1336', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'I1213', 'Functions.Hardware.HardwareConfiguration.SapOrderId.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11676', 'I1204', 'I1359', 'I1336', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'I121z', 'Functions.Hardware.HardwareConfiguration.SapOrderId.Existing', null, null, null, null, null, null, null);
