/*
--#########################################################################
--
-- Script Name  :  $Workfile:   upd_srd_bks_static_configuration_3.sql  $ 
-- Header		:  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_static_configuration_3.sql-arc   1.0   Jan 10 2008 11:09:46   huptasch  $ 
-- Revision		:  $Revision:   1.0  $
-- 
---------------------------------------------------------------------------
--
-- Description:
--
-- IT-19578 "Bestandskundenservice AAW-RD R1.2 Phase 2"
-- Reference data for BKS customer data mapping
--
--
--#########################################################################*/

alter session set nls_date_format = 'DD.MM.YYYY';

delete from BKS_STATIC_CONFIGURATION;

INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('CUSTOMER;CATEGORY_RD;JuristischePerson', '.Bestand.(JuristischePerson).Kundenkategorie', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('CUSTOMER;CLASSIFICATION_RD;JuristischePerson', '.Bestand.(JuristischePerson).Kundenklasse', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('CUSTOMER;CUSTOMER_NUMBER;JuristischePerson', '.Bestand.(JuristischePerson).Kundennummer', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('CUSTOMER;P_SERVICE_PROVIDER_CODE;JuristischePerson', '.Bestand.(JuristischePerson).ServiceProviderCode', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('CUSTOMER;CATEGORY_RD;NatuerlichePerson', '.Bestand.(NatuerlichePerson).Kundenkategorie', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('CUSTOMER;CLASSIFICATION_RD;NatuerlichePerson', '.Bestand.(NatuerlichePerson).Kundenklasse', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('CUSTOMER;CUSTOMER_NUMBER;NatuerlichePerson', '.Bestand.(NatuerlichePerson).Kundennummer', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('CUSTOMER;P_SERVICE_PROVIDER_CODE;NatuerlichePerson', '.Bestand.(NatuerlichePerson).ServiceProviderCode', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('COMMISSIONING_INFORMATION;CIO_DATA;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.VoNummer', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_CONTRACT;P_MIN_PERIOD;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.MVLZ', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_CONTRACT;P_TERM_END_DATE;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.LaufzeitEndeDatum', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_CONTRACT;TERM_START_DATE;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.MindestvertragslaufzeitBeginn', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;P_MIN_PERIOD;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.MVLZ', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;P_TERM_END_DATE;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.LaufzeitEndeDatum', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;PRICING_STRUCTURE_CODE;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.PreisStrukturCode', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;PRODUCT_CODE;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.ProduktCode', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;PRODUCT_VERSION_CODE;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.VersionCode', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;TERM_START_DATE;Internet', '.Bestand.Auftragsposition.Internet.NutzungsmodellInternet.MindestvertragslaufzeitBeginn', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('COMMISSIONING_INFORMATION;CIO_DATA;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.VoNummer', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_CONTRACT;P_MIN_PERIOD;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.MVLZ', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_CONTRACT;P_TERM_END_DATE;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.LaufzeitEndeDatum', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_CONTRACT;TERM_START_DATE;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.MindestvertragslaufzeitBeginn', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;P_MIN_PERIOD;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.MVLZ', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;P_TERM_END_DATE;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.LaufzeitEndeDatum', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;PRICING_STRUCTURE_CODE;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.PreisStrukturCode', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;PRODUCT_CODE;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.ProduktCode', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;PRODUCT_VERSION_CODE;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.VersionCode', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));
INSERT INTO BKS_STATIC_CONFIGURATION (VALUE_ID, TARGET_ATTRIBUTE_PATH, VALID_FROM, VALID_UNTIL)
    VALUES ('P_PRODUCT_COMMITMENT;TERM_START_DATE;Sprache', '.Bestand.Auftragsposition.Sprache.NutzungsmodellSprache.MindestvertragslaufzeitBeginn', TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'), TO_DATE ('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'));

