/*
--#########################################################################
--
-- Script Name          :  $Workfile:   upd_crd_general_code_item_wbci_block.sql  $ 
-- Header               :  $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_crd_general_code_item_wbci_block.sql-arc   1.0   Feb 26 2015 15:54:12   makuier  $ 
-- Revision             :  $Revision:   1.0  $
-- 
---------------------------------------------------------------------------
--
--  IT-k-25454
-- 
--
--
--
--#########################################################################*/

ALTER session SET nls_date_format='DD.MM.YYYY HH24:MI:SS';


DELETE FROM general_code_item
WHERE GROUP_CODE = 'WBCI_BLOCK';

DELETE FROM general_code_group
WHERE GROUP_CODE = 'WBCI_BLOCK';
-------------------------------------------------------
INSERT INTO GENERAL_CODE_GROUP (GROUP_CODE, DESCRIPTION, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER, DESCRIPTION_TRANSLATION_ID, COMPONENT, DATA_TYPE, RESPONSIBLE)
    VALUES ('WBCI_BLOCK', 'WBCI Blocking Customer Intention', 'crd_user', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 1004, NULL, 'CCM', NULL, 'CCM Entwicklung');
	

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'AddDSL', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Add DSL', 'Add DSL', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'CancelOrder', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Cancel order', 'Cancel order', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'ChgAccessNumbers', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Change Access Numbers', 'Change Access Numbers', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'ChgCustomerData', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Change Customer Data', 'Change Customer Data', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'ContrPartChange', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Contract Partner Change', 'Contract Partner Change', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'DeactCustomer', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Deactivate Customer', 'Deactivate Customer', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'LineChange', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'LineChange', 'LineChange', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'ProviderChange', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'ProviderChange', 'ProviderChange', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'Relocation', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Relocation', 'Relocation', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'TerminateDSL', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Termination DSL', 'Termination DSL', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'Winback', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Winback', 'Winback', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'RelocationClone', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Relocation Clone', 'Relocation Clone', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'RelocationDeact', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Relocation Deact', 'Relocation Deact', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'LineChangeClone', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Line Change Clone', 'Line Change Clone', NULL, NULL, 'crd_user', sysdate, 1);

INSERT INTO GENERAL_CODE_ITEM (GROUP_CODE, VALUE, EFFECTIVE_DATE, EFFECTIVE_STATUS, DESCRIPTION, SHORT_DESCRIPTION, DESCRIPTION_TRANSLATION_ID, SHORT_DESCRIPTION_TRANS_ID, AUDIT_UPDATE_USER_ID, AUDIT_UPDATE_DATE_TIME, UPDATE_NUMBER)
    VALUES ('WBCI_BLOCK', 'LineChangeDeact', TO_DATE ('01.04.1999 12:31:12', 'DD.MM.YYYY HH24:MI:SS'), 'ACTIVE', 'Line Change Deact', 'Line Change Deact', NULL, NULL, 'crd_user', sysdate, 1);
