/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_132.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_132.sql-arc   1.0   Jul 28 2011 20:23:34   wlazlow  $ 
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- SPN-BKS-000114356, Handling of the V0114 service was added for VI202 product.
--
--
--#########################################################################*/



delete FROM BKS_GENERIC_CONFIGURATION t where t.value_id in
('BKSGC_11594', 'BKSGC_11595', 'BKSGC_11596', 
 'BKSGC_11597', 'BKSGC_11598', 'BKSGC_11599', 
 'BKSGC_11600', 'BKSGC_11601', 'BKSGC_11602', 
 'BKSGC_11603', 'BKSGC_11604');






insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11594', 'VI202', 'V0114', 'V0112', null, null, null, '00000000', 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.ArticleNumber.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11595', 'VI202', 'V0114', 'V0112', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', 'HardwareTyp', to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.HardwareType.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11596', 'VI202', 'V0114', 'V0110', 3, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.Forename.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11597', 'VI202', 'V0114', 'V0110', 2, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.Name.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11598', 'VI202', 'V0114', 'V0110', 1, null, null, null, 'CONFIGURED_VALUE', 'defaultSalutation', 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.SalutationDescription.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11599', 'VI202', 'V0114', 'V0119', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.ShippingCosts.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11600', 'VI202', 'V0114', 'V0184', null, null, null, null, 'CONFIGURED_VALUE', 'convertToBoolean', 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.ZeroChargeIndicator.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11601', 'VI202', 'V0114', 'V0114', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.SubventionCode.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11602', 'VI202', 'V0114', '-', null, null, null, 'Doku - Kein Versand', 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.OrderReason.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11603', 'VI202', 'V0114', 'V0109', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.SerialNumber.Existing', null, null, null, null, null, null, null);
insert into BKS_GENERIC_CONFIGURATION (VALUE_ID, SOURCE_PRODUCT_CODE, SOURCE_SERVICE_CODE, SOURCE_SERVICE_CHAR_CODE, SOURCE_FIELD_NUMBER, SOURCE_COLUMN, TARGET_ATTRIBUTE_PATH, DEFAULT_VALUE, VALUE_TYPE, APPLY_METHOD, TARGET_MULTIPLE_OCCURRENCE, RDS_ID, VALID_FROM, VALID_UNTIL, PARENT_SERVICE_CODE, SOM_ATTRIBUTE_PATH, PREFIX, DEPENDENT_CHAR_CODE, MAIN_BUNDLE_ACCESS, SID_ATTRIBUTE_PATH, OPEN_ORDER_INDICATOR, FIXED_VALUE, INTRODUCTION_VERSION)
values ('BKSGC_11604', 'VI202', 'V0114', 'V0116', null, null, null, null, 'CONFIGURED_VALUE', null, 'N', null, to_date('01-01-1979', 'dd-mm-yyyy'), to_date('01-01-3000', 'dd-mm-yyyy'), 'VI002', 'Functions.Hardware.HardwareConfiguration.ArticleName.Existing', null, null, null, null, null, null, null);


