/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_75.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_75.sql-arc   1.0   Nov 02 2010 10:11:18   makuier  $ 
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- Upgrade to AAW-Sprache 132 - changes in ASK structure
--
--#########################################################################*/

UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8330'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8329'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8328'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8327'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8326'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8325'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8324'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8323'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8322'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8321'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8320'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8319'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8318'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8317'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8316'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8315'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8314'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8313'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8312'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8311'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8310'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8309'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8308'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8307'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8300'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8301'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8302'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8303'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8304'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8305'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8306'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8501'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8298'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8297'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8296'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8295'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8294'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8500'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8299'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8293'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8292'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8291'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8290'; 
UPDATE BKS_GENERIC_CONFIGURATION SET APPLY_METHOD = 'convertToBigDecimal' WHERE VALUE_ID = 'BKSGC_8289';
