/*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_122.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_122.sql-arc   1.1   Jun 15 2011 15:54:04   makuier  $ 
-- Revision   : $Revision:   1.1  $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- Upgrade to AAW-Sprache 132 - changes in ASK structure
--
--#########################################################################*/

UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11138';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11135';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10972';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10970';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10968';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11058';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11056';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11053';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11051';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11049';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11047';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11046';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11044';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11042';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11040';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11038';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11036';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11034';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11032';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11030';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11028';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11026';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11024';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11022';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11020';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11018';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11016';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11014';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11012';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11010';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11008';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11006';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11004';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11002';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11000';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10998';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10996';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10994';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10992';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10990';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10988';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10986';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10984';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10982';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10980';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10978';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10976';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10974';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11137';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11134';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10971';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10969';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10967';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11057';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11055';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11054';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11052';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11050';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11048';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11045';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11043';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11041';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11039';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11037';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11035';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11033';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11031';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11029';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11027';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11025';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11023';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11021';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11019';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11017';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11015';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11013';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11011';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11009';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11007';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11005';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11003';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_11001';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10999';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10997';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10995';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10993';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10991';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10989';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10987';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10985';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10983';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10981';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10979';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10977';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10975';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10973';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10966';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10965';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10964';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10963';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10962';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10961';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10960';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10959';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10958';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10957';
UPDATE BKS_GENERIC_CONFIGURATION SET INTRODUCTION_VERSION = 'BKS-005' WHERE VALUE_ID = 'BKSGC_10956';

UPDATE BKS_GENERIC_CONFIGURATION SET 
INTRODUCTION_VERSION = 'BKS-005', 
SID_ATTRIBUTE_PATH = 'ProductOfferingSubscription.ProductOfferingOccurrence.Product.CharacteristicValue.MappedValue'
WHERE VALUE_ID IN ('BKSGC_10955');