                                                         /*
--#########################################################################
--
-- Script name: $Workfile:   upd_srd_bks_generic_configuration_259.sql  $ 
-- Header     : $Header:   //PVCS_BKS/archives/BKS/DB/dbscripts/upd_srd_bks_generic_configuration_259.sql-arc   1.0   Oct 15 2015 11:26:12   makuier  $ 
-- Revision   : $Revision:   1.0  $ 
--
---------------------------------------------------------------------------
--
-- Description
--
-- Upgrade to AAW-Sprache 132 - changes in ASK structure
--
--#########################################################################*/

DELETE FROM BKS_GENERIC_CONFIGURATION WHERE VALUE_ID IN (
'BKSGC_15475','BKSGC_15476');

Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION)
  values ('BKSGC_15475','VI207','VI250','VI05A',NULL,NULL,NULL,NULL,'CONFIGURED_VALUE',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Accesses.OneNetBusiness.OneNetBusinessConfiguration.NumberOfVoiceChannels.Existing',NULL,NULL,NULL,NULL,NULL,NULL,'17.0');

Insert into BKS_GENERIC_CONFIGURATION (VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL,PARENT_SERVICE_CODE,SOM_ATTRIBUTE_PATH,PREFIX,DEPENDENT_CHAR_CODE,MAIN_BUNDLE_ACCESS,SID_ATTRIBUTE_PATH,OPEN_ORDER_INDICATOR,FIXED_VALUE,INTRODUCTION_VERSION)
  values ('BKSGC_15476','VI207','VI250','V0082',NULL,NULL,NULL,NULL,'CONFIGURED_VALUE',NULL,'N',NULL,TO_DATE ('01.01.1979 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),TO_DATE('01.01.3000 00:00:00', 'DD.MM.YYYY HH24:MI:SS'),NULL,'Accesses.OneNetBusiness.OneNetBusinessConfiguration.Carrier.Existing',NULL,NULL,NULL,NULL,NULL,NULL,'17.0');

