/*
--#########################################################################
--
-- Script name: $Workfile $ 
-- Header     : $Header $ 
-- Revision   : $Revision $ 
--
---------------------------------------------------------------------------
--
-- Description
--
--
--#########################################################################*/

alter session set nls_date_format = 'DD.MM.YYYY';

delete from BKS_GENERIC_CONFIGURATION
where VALUE_ID >= 'BKSGC_0171' and VALUE_ID <= 'BKSGC_0258';

insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0171','V0001','V0001','V0001','3',null,'Sprache.Anschluss.Rufnummerliste.Hauptrufnummer',null,'ACCESS_NUMBER','prefixZero','N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0172','V0001','V0001','V0014',null,'STREET_NUMBER','Sprache.Anschluss.Lokationsadresse.Hausnummer',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0173','V0001','V0001','V0014',null,'STREET_NUMBER_SUFFIX','Sprache.Anschluss.Lokationsadresse.Hausnummerzusatz',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0174','V0001','V0001','V0014',null,'COUNTRY_RD','Sprache.Anschluss.Lokationsadresse.Land',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0175','V0001','V0001','V0014',null,'CITY_NAME','Sprache.Anschluss.Lokationsadresse.Ort',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0176','V0001','V0001','V0014',null,'CITY_SUFFIX_NAME','Sprache.Anschluss.Lokationsadresse.Ortszusatz',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0177','V0001','V0001','V0014',null,'POSTAL_CODE','Sprache.Anschluss.Lokationsadresse.PLZ',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0178','V0001','V0001','V0014',null,'POST_OFFICE_BOX','Sprache.Anschluss.Lokationsadresse.Postfach',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0179','V0001','V0001','V0014',null,'STREET_NAME','Sprache.Anschluss.Lokationsadresse.Strasse',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0180','V0001','V0001','V0070','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer2',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0181','V0001','V0001','V0071','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer3',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0182','V0001','V0001','V0072','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer4',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0183','V0001','V0001','V0073','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer5',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0184','V0001','V0001','V0074','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer6',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0185','V0001','V0001','V0075','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer7',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0186','V0001','V0001','V0076','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer8',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0187','V0001','V0001','V0077','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer9',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0188','V0001','V0001','V0078','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer10',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0189','V0001','V0001','V0127',null,null,'Sprache.Anschluss.Name',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0190','V0001','V0001','V0128',null,null,'Sprache.Anschluss.Vorname',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0191','V0001','V0001','V0129',null,null,'Sprache.Anschluss.ZweiterAnschlussinhaber.Name',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0192','V0001','V0001','V0130',null,null,'Sprache.Anschluss.ZweiterAnschlussinhaber.Vorname',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0193','V0001','V0002','V0001','3',null,'Sprache.Anschluss.Rufnummerliste.Hauptrufnummer',null,'ACCESS_NUMBER','prefixZero','N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0194','V0001','V0002','V0014',null,'STREET_NUMBER','Sprache.Anschluss.Lokationsadresse.Hausnummer',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0195','V0001','V0002','V0014',null,'STREET_NUMBER_SUFFIX','Sprache.Anschluss.Lokationsadresse.Hausnummerzusatz',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0196','V0001','V0002','V0014',null,'COUNTRY_RD','Sprache.Anschluss.Lokationsadresse.Land',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0197','V0001','V0002','V0014',null,'CITY_NAME','Sprache.Anschluss.Lokationsadresse.Ort',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0198','V0001','V0002','V0014',null,'CITY_SUFFIX_NAME','Sprache.Anschluss.Lokationsadresse.Ortszusatz',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0199','V0001','V0002','V0014',null,'POSTAL_CODE','Sprache.Anschluss.Lokationsadresse.PLZ',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0200','V0001','V0002','V0014',null,'POST_OFFICE_BOX','Sprache.Anschluss.Lokationsadresse.Postfach',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0201','V0001','V0002','V0014',null,'STREET_NAME','Sprache.Anschluss.Lokationsadresse.Strasse',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0202','V0001','V0002','V0070','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer2',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0203','V0001','V0002','V0071','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer3',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0204','V0001','V0002','V0072','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer4',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0205','V0001','V0002','V0073','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer5',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0206','V0001','V0002','V0074','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer6',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0207','V0001','V0002','V0075','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer7',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0208','V0001','V0002','V0076','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer8',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0209','V0001','V0002','V0077','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer9',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0210','V0001','V0002','V0078','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer10',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0211','V0001','V0002','V0127',null,null,'Sprache.Anschluss.Name',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0212','V0001','V0002','V0128',null,null,'Sprache.Anschluss.Vorname',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0213','V0001','V0002','V0129',null,null,'Sprache.Anschluss.ZweiterAnschlussinhaber.Name',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0214','V0001','V0002','V0130',null,null,'Sprache.Anschluss.ZweiterAnschlussinhaber.Vorname',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0215','V0001','V0004','V0001','3',null,'Sprache.Anschluss.Rufnummerliste.Hauptrufnummer',null,'ACCESS_NUMBER','prefixZero','N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0216','V0001','V0004','V0014',null,'STREET_NUMBER','Sprache.Anschluss.Lokationsadresse.Hausnummer',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0217','V0001','V0004','V0014',null,'STREET_NUMBER_SUFFIX','Sprache.Anschluss.Lokationsadresse.Hausnummerzusatz',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0218','V0001','V0004','V0014',null,'COUNTRY_RD','Sprache.Anschluss.Lokationsadresse.Land',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0219','V0001','V0004','V0014',null,'CITY_NAME','Sprache.Anschluss.Lokationsadresse.Ort',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0220','V0001','V0004','V0014',null,'CITY_SUFFIX_NAME','Sprache.Anschluss.Lokationsadresse.Ortszusatz',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0221','V0001','V0004','V0014',null,'POSTAL_CODE','Sprache.Anschluss.Lokationsadresse.PLZ',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0222','V0001','V0004','V0014',null,'POST_OFFICE_BOX','Sprache.Anschluss.Lokationsadresse.Postfach',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0223','V0001','V0004','V0014',null,'STREET_NAME','Sprache.Anschluss.Lokationsadresse.Strasse',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0224','V0001','V0004','V0070','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer2',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0225','V0001','V0004','V0071','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer3',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0226','V0001','V0004','V0072','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer4',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0227','V0001','V0004','V0073','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer5',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0228','V0001','V0004','V0074','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer6',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0229','V0001','V0004','V0075','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer7',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0230','V0001','V0004','V0076','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer8',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0231','V0001','V0004','V0077','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer9',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0232','V0001','V0004','V0078','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer10',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0233','V0001','V0004','V0127',null,null,'Sprache.Anschluss.Name',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0234','V0001','V0004','V0128',null,null,'Sprache.Anschluss.Vorname',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0235','V0001','V0004','V0129',null,null,'Sprache.Anschluss.ZweiterAnschlussinhaber.Name',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0236','V0001','V0004','V0130',null,null,'Sprache.Anschluss.ZweiterAnschlussinhaber.Vorname',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0237','V0001','V0044','V0001','3',null,'Sprache.Anschluss.Rufnummerliste.Hauptrufnummer',null,'ACCESS_NUMBER','prefixZero','N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0238','V0001','V0044','V0014',null,'STREET_NUMBER','Sprache.Anschluss.Lokationsadresse.Hausnummer',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0239','V0001','V0044','V0014',null,'STREET_NUMBER_SUFFIX','Sprache.Anschluss.Lokationsadresse.Hausnummerzusatz',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0240','V0001','V0044','V0014',null,'COUNTRY_RD','Sprache.Anschluss.Lokationsadresse.Land',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0241','V0001','V0044','V0014',null,'CITY_NAME','Sprache.Anschluss.Lokationsadresse.Ort',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0242','V0001','V0044','V0014',null,'CITY_SUFFIX_NAME','Sprache.Anschluss.Lokationsadresse.Ortszusatz',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0243','V0001','V0044','V0014',null,'POSTAL_CODE','Sprache.Anschluss.Lokationsadresse.PLZ',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0244','V0001','V0044','V0014',null,'POST_OFFICE_BOX','Sprache.Anschluss.Lokationsadresse.Postfach',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0245','V0001','V0044','V0014',null,'STREET_NAME','Sprache.Anschluss.Lokationsadresse.Strasse',null,'ADDRESS',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0246','V0001','V0044','V0070','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer2',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0247','V0001','V0044','V0071','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer3',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0248','V0001','V0044','V0072','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer4',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0249','V0001','V0044','V0073','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer5',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0250','V0001','V0044','V0074','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer6',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0251','V0001','V0044','V0075','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer7',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0252','V0001','V0044','V0076','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer8',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0253','V0001','V0044','V0077','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer9',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0254','V0001','V0044','V0078','3',null,'Sprache.Anschluss.Rufnummerliste.Rufnummer10',null,'ACCESS_NUMBER',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0255','V0001','V0044','V0127',null,null,'Sprache.Anschluss.Name',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0256','V0001','V0044','V0128',null,null,'Sprache.Anschluss.Vorname',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0257','V0001','V0044','V0129',null,null,'Sprache.Anschluss.ZweiterAnschlussinhaber.Name',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
insert into BKS_GENERIC_CONFIGURATION
(VALUE_ID,SOURCE_PRODUCT_CODE,SOURCE_SERVICE_CODE,SOURCE_SERVICE_CHAR_CODE,SOURCE_FIELD_NUMBER,SOURCE_COLUMN,TARGET_ATTRIBUTE_PATH,DEFAULT_VALUE,VALUE_TYPE,APPLY_METHOD,TARGET_MULTIPLE_OCCURRENCE,RDS_ID,VALID_FROM,VALID_UNTIL)
values
('BKSGC_0258','V0001','V0044','V0130',null,null,'Sprache.Anschluss.ZweiterAnschlussinhaber.Vorname',null,'CONFIGURED_VALUE',null,'N',null,'01.01.1979','01.01.3000');
